@echo off
copy /b /y .\DistributedProcessing\Core\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\MessagingService\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\ModelGenerator\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\partitionerAdm\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\partitionerService\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\SolverRunner\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\DistributedProcessing\WorkerNodeService\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\Messaging\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\MessagingService\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\Analytics\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\Math\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\Sys\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y .\Wcf\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y ..\OdePackInterop\OdePackInterop\bin\x64\Release\*.nupkg  ..\Packages\
copy /b /y ..\AddressProcessor\AddressProcessor\bin\Release\*.nupkg  ..\Packages\
copy /b /y ..\Berreman\Berreman\Analytics\bin\x64\Release\*.nupkg  ..\Packages\ 
copy /b /y ..\Berreman\Berreman\Berreman\bin\x64\Release\*.nupkg  ..\Packages\ 
copy /b /y ..\Berreman\Berreman\OpticalProperties\bin\x64\Release\*.nupkg  ..\Packages\ 
copy /b /y ..\Berreman\MathNetNumerics\FSharp\bin\x64\Release\*.nupkg  ..\Packages\ 
copy /b /y ..\Berreman\MathNetNumerics\Numerics\bin\x64\Release\*.nupkg  ..\Packages\ 
copy /b /y ..\DryIoc\.dist\packages\*.nupkg  ..\Packages\
