// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softellect.Migrations.MessagingService;

#nullable disable

namespace Softellect.Migrations.MessagingService.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20250506151227_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Softellect.Migrations.Common.DeliveryType", b =>
                {
                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("deliveryTypeId");

                    b.Property<string>("DeliveryTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("deliveryTypeName");

                    b.HasKey("DeliveryTypeId");

                    b.HasIndex("DeliveryTypeName")
                        .IsUnique();

                    b.ToTable("DeliveryType");
                });

            modelBuilder.Entity("Softellect.Migrations.Common.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("messageId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdOn");

                    b.Property<int>("DataVersion")
                        .HasColumnType("int")
                        .HasColumnName("dataVersion");

                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("deliveryTypeId");

                    b.Property<byte[]>("MessageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("messageData");

                    b.Property<long>("MessageOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("messageOrder");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageOrder"));

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipientId");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("senderId");

                    b.HasKey("MessageId");

                    b.HasIndex("DeliveryTypeId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Softellect.Migrations.Common.Message", b =>
                {
                    b.HasOne("Softellect.Migrations.Common.DeliveryType", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("DeliveryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryType");
                });
#pragma warning restore 612, 618
        }
    }
}
